name: Release to npm

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js with pnpm
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install
        working-directory: ./packages/global-inject

      - name: Publish to npm
        run: pnpm publish
        working-directory: ./packages/global-inject
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}